#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

echo "Best School"
echo "Best School"
echo "Best School"
echo "Best School"
echo "Best School"
echo "Best School"
echo "Best School"
echo "Best School"
echo "Best School"
echo "Best School"


